services:
  # API service (Express)
  api:
    image: calvicii/onloc-api
    container_name: onloc-api
    environment:
      - DATABASE_URL=postgresql://onloc:onloc@db:5432/onloc?schema=public
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # UI service (React)
  ui:
    image: calvicii/onloc-ui
    container_name: onloc-ui
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_SERVER_URL=/
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

  # Nginx for proxying requests
  nginx:
    image: nginx:latest
    container_name: onloc-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "6144:6144"
    depends_on:
      - api
      - ui
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: onloc-db
    environment:
      POSTGRES_DB: onloc
      POSTGRES_USER: onloc
      POSTGRES_PASSWORD: onloc
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onloc"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
    name: onloc-network
